# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set env var MODULE
      run: echo ::set-env name=MODULE::$(jq -r '.package_info.module_name' setup.json)
    - name: Set env var REPO
      run: echo ::set-env name=REPO::$(jq -r '.package_info.friendly_name' setup.json)

    - name: Install dependencies
      run: bash .ci/install.sh

    - name: Test
      run: bash .ci/test.sh

    - name: Uplod test coverage
      run: bash .ci/upload_test_coverage.sh

    - name: Push docs
      run: bash .ci/generate_docs.sh

    - name: Push docs
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: docs/build/html
